[package]
name = "rp-spi-image"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.5"
fontdue = "0.7.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
gif = "0.12"